# Generated by Django 5.2 on 2025-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='z.B. Ich mag an dir...', max_length=100, verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.CharField(help_text='z.B. Max Mustermann', max_length=20, verbose_name='Empfänger'),
        ),
    ]
